volumes:
  postgres_data:

services:
  php:
    container_name: ${APP_NAME}-php
    build:
      args:
        user: ${USER}
        uid: ${UID}
      context: php
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATEBASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      COMPOSER_MEMORY_LIMIT: -1
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=Docker}
    volumes:
      - ../:/var/www
      - ./docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    working_dir: /var/www
    ports:
      - ${PHP_PORT}:9000
    networks:
      - app
    depends_on:
      - db
  nginx:
    container_name: ${APP_NAME}-nginx
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile
    links:
      - php
      - db
    depends_on:
      - php
    ports:
      - ${NGINX_PORT_ON_HOST}:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../.env:/var/www/.env
      - ../:/var/www
    environment:
      - PHP_FPM_HOST=${APP_NAME}-php
      - PHP_FPM_PORT=9000
    networks:
      - app
  db:
    container_name: ${APP_NAME}-db
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    networks:
      - app
networks:
  app:
    driver: bridge
